### ISSUE TITLE
linking .XCompose lead to ALL GTK4 compiled apps crash

### ISSUE THREAD

**Issue by joihn** [rvaiya/keyd#537]
to get unicode support (cf man page ), I did:
`ln -s /usr/share/keyd/keyd.compose ~/.XCompose`
Unicode key remap works well.

however, now all my gtk4 app crash (including the GTK4 demo) (including ubuntu 22 gnome-extension-app)

steps:
```
sudo apt install gtk-4-examples
gtk4-demo-application


Gtk:ERROR:../../../gtk/gtkcomposetable.c:981:parser_get_compose_table: assertion failed: (data[first_pos + i] <= data[first_pos + i + 1])
Bail out! Gtk:ERROR:../.
```

full backtrace:
```
**
Gtk:ERROR:../../../gtk/gtkcomposetable.c:981:parser_get_compose_table: assertion failed: (data[first_pos + i] <= data[first_pos + i + 1])
Bail out! Gtk:ERROR:../../../gtk/gtkcomposetable.c:981:parser_get_compose_table: assertion failed: (data[first_pos + i] <= data[first_pos + i + 1])

Thread 4 "pool-gtk4-demo" received signal SIGABRT, Aborted.
[Switching to Thread 0x7ffff202b640 (LWP 24197)]
__pthread_kill_implementation (no_tid=0, signo=6, threadid=140737253652032) at ./nptl/pthread_kill.c:44
44	./nptl/pthread_kill.c: No such file or directory.



(gdb) bt
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=140737253652032) at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=140737253652032) at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=140737253652032, signo=signo@entry=6) at ./nptl/pthread_kill.c:89
#3  0x00007ffff62bd476 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#4  0x00007ffff62a37f3 in __GI_abort () at ./stdlib/abort.c:79
#5  0x00007ffff7692b57 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#6  0x00007ffff76ec70f in g_assertion_message_expr () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#7  0x00007ffff78c50e3 in parser_get_compose_table (parser=0x7fffe807dd60) at ../../../gtk/gtkcomposetable.c:981
#8  0x00007ffff79410b4 in gtk_compose_table_parse (found_include=<synthetic pointer>, compose_file=0x7fffe80e8450 "/home/maxime/.XCompose") at ../../../gtk/gtkcomposetable.c:1067
#9  gtk_compose_table_new_with_file (compose_file=0x7fffe80e8450 "/home/maxime/.XCompose") at ../../../gtk/gtkcomposetable.c:1143
#10 add_compose_table_from_file (compose_file=compose_file@entry=0x7fffe80e8450 "/home/maxime/.XCompose") at ../../../gtk/gtkimcontextsimple.c:220
#11 0x00007ffff79417b1 in gtk_im_context_simple_init_compose_table () at ../../../gtk/gtkimcontextsimple.c:296
#12 init_compose_table_thread_cb (task=<optimized out>, source_object=<optimized out>, task_data=<optimized out>, cancellable=<optimized out>) at ../../../gtk/gtkimcontextsimple.c:366
#13 0x00007ffff74ed194 in  () at /lib/x86_64-linux-gnu/libgio-2.0.so.0
#14 0x00007ffff76fb6b4 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#15 0x00007ffff76f8a51 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#16 0x00007ffff630fb43 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
#17 0x00007ffff63a1a00 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
(gdb) 

```

related threads:
https://gitlab.gnome.org/GNOME/gtk/-/issues/4990
https://bugs.launchpad.net/ubuntu/+source/gtk4/+bug/2027571

my keyd.compose (it seems there is something gtk4 does not like):
```
cat /usr/share/keyd/keyd.compose                       
<Cancel> <0> <0> <0> : ""
<Cancel> <0> <0> <1> : ""
<Cancel> <0> <0> <2> : ""
<Cancel> <0> <0> <3> : ""
<Cancel> <0> <0> <4> : "
                        "
<Cancel> <0> <0> <5> : "
"
<Cancel> <0> <0> <6> : ""
<Cancel> <0> <0> <7> : ""
<Cancel> <0> <0> <8> : ""
<Cancel> <0> <0> <9> : "	"
<Cancel> <0> <0> <a> : ""
<Cancel> <0> <0> <b> : ""
<Cancel> <0> <0> <c> : ""
<Cancel> <0> <0> <e> : ""
<Cancel> <0> <0> <f> : ""
<Cancel> <0> <0> <g> : ""
<Cancel> <0> <0> <i> : ""
<Cancel> <0> <0> <j> : ""
<Cancel> <0> <0> <k> : ""
<Cancel> <0> <0> <l> : ""
<Cancel> <0> <0> <m> : ""
<Cancel> <0> <0> <n> : ""
<Cancel> <0> <0> <o> : ""
<Cancel> <0> <0> <q> : "
<Cancel> <0> <0> <r> : "
ancel> <0> <0> <s> : ""


```

ubuntu 22.04 running X11

**Comment by joihn** [comment]
removing the symlink solve the issue

**Comment by joihn** [comment]
Actually cat does not show the whole file, here is the whole file

[dotXCompose.txt](https://github.com/rvaiya/keyd/files/12062764/dotXCompose.txt)

**Comment by joihn** [comment]
seems related to https://github.com/rvaiya/keyd/issues/273

**Comment by joihn** [comment]
I can confirm that after pruning to less than 1000 lines, GTK4 is happy (all the symbol that interrested me where in the beginning anyway). 

For beginner struggling to find a tool capable of handling such a big file, I recommend vim.

Maybe keyd should ship be default with a pruned XCompose ? And let the user enable the longer one if desired ?
